Feature/login/clk32 887 login view
ClearKeep/ck-ios pull request #11
Opened 2022-03-05 04:27 UTC by dongnh99

## Prerequisite
- [x] Self-review :monocle_face:
- [x] No Crashes ☠️
---

### Root cause
- // Add Login view

### Solution
- // Explain how you fix it

### Impact
- // Login view

### Screenshots (Optional)
- // Capture affected screens
- Light
![Simulator Screen Shot - iPhone 12 Pro - 2022-03-05 at 11 23 42](https://user-images.githubusercontent.com/100552659/156867518-03990b2c-6958-43ab-be72-ecc2fdda1be6.png)
- Dark
![Simulator Screen Shot - iPhone 12 Pro - 2022-03-05 at 11 27 30](https://user-images.githubusercontent.com/100552659/156867651-1f188b5e-2bc0-4f15-ab4c-b94c79461602.png)

2022-03-07 07:44 UTC, namnh92 commented
<!--
  0 Errors
  1 Warning: Big PR
  0 Messages
  9 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

- [ ] I understand that "General.Email" is now existed in Localized service

- [ ] I understand that "General.Password" is now existed in Localized service

- [ ] I understand that "Login.AdvancedServerSettings" is now existed in Localized service

- [ ] I understand that "Login.AppVersion:1.1.1" is now existed in Localized service

- [ ] I understand that "Login.Don'tHaveAnAccount?" is now existed in Localized service

- [ ] I understand that "Login.ForgotPassword?" is now existed in Localized service

- [ ] I understand that "Login.SignIn" is now existed in Localized service

- [ ] I understand that "Login.SignInWith" is now existed in Localized service

- [ ] I understand that "Login.SignUp" is now existed in Localized service

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2022-03-07 10:09 UTC, namnh92 requested changes

2022-03-07 10:09 UTC, namnh92 commented on ClearKeep/Scenes/Login/Views/LoginContentView.swift
> +	var backgroundSignInBt: LinearGradient {
@dongnh99 : Do not abbreviate!
```suggestion
	var backgroundSignInButton: LinearGradient {
```

2022-03-07 10:09 UTC, namnh92 commented on ClearKeep/Scenes/Login/Views/LoginContentView.swift
> +	var foregroundColorViewBt: Color {
@dongnh99 : Do not abbreviate!
```suggestion
	var foregroundColorViewButton: Color {
```

2022-03-07 10:09 UTC, namnh92 commented on ClearKeep/Scenes/Login/Views/LoginContentView.swift
> +		LinearGradient(gradient: Gradient(colors: [.white, .white]), startPoint: .leading, endPoint: .trailing)
@dongnh99 : Using AppThem.shared.colorSet. Do not hard code color !

2022-03-07 10:09 UTC, namnh92 commented on ClearKeep/Scenes/Login/Views/LoginContentView.swift
> +		LinearGradient(gradient: Gradient(colors: [.white, .white]), startPoint: .leading, endPoint: .trailing)
@dongnh99 : Using AppThem.shared.colorSet. Do not hard code color !

2022-03-07 10:09 UTC, namnh92 commented on ClearKeep/Scenes/Login/Views/LoginContentView.swift
> +		LinearGradient(gradient: Gradient(colors: [.black, .black]), startPoint: .leading, endPoint: .trailing)
@dongnh99 : Using AppThem.shared.colorSet. Do not hard code color !

2022-03-07 10:09 UTC, namnh92 commented on ClearKeep/Scenes/Login/Views/LoginContentView.swift
> +				}
@dongnh99 : Need apply dark/light mode to background/ foreground

2022-03-07 10:09 UTC, namnh92 commented on ClearKeep/Scenes/Login/Views/LoginContentView.swift
> +	static let widthSignInBt = UIScreen.main.bounds.width - 30.0
@dongnh99 : Do not abbreviate!
Using padding not using screen width

2022-03-07 10:09 UTC, namnh92 commented on ClearKeep/Scenes/Login/Views/LoginContentView.swift
> +		NavigationView {
@dongnh99 : Subviews do not contain NavigationView

2022-03-07 10:09 UTC, namnh92 commented on ClearKeep/Scenes/Login/Views/LoginContentView.swift
> +						.frame(width: Constant.widthLogo, height: Constant.heightLogo)
@dongnh99 Using CGSize for short code

2022-03-07 10:09 UTC, namnh92 commented on ClearKeep/Scenes/Login/Views/LoginContentView.swift
> +						.frame(width: Constant.widthSignInBt, height: Constant.heightBt)
@dongnh99 : Do not fix width of button. Please using padding

2022-03-07 14:01 UTC, dongnh99 commented on ClearKeep/Scenes/Login/Views/LoginContentView.swift
> +				}
this foreground is white in both dark and light mode

2022-03-09 03:37 UTC, namnh92 approved these changes

2022-03-09 03:38 UTC, merged