Bugs/AdvancedServer/CLK32-Fixbug Advanced Server
ClearKeep/ck-ios pull request #113
Opened 2022-08-03 07:28 UTC by Minhdn1

## Prerequisite
- [x] Self-review :monocle_face:
- [x] No Crashes ☠️
---

### Root cause
- // Explain what you have done

### Solution
- // Explain how you fix it

### Impact
- // List of affected components/modules

### Screenshots (Optional)
- // Capture affected screens

2022-08-03 08:44 UTC, vmo-klinh requested changes

2022-08-03 08:44 UTC, vmo-klinh commented on ClearKeep/App/Resources/Localize.strings
> +"General.Closse" = "Closse";
General.'Closse': typo

2022-08-03 08:44 UTC, vmo-klinh commented on ClearKeep/App/Resources/Localize.strings
> +"AdvancedServer.Message.Error" = "Wrong server URL.Please try again";
Missing space

2022-08-03 09:01 UTC, Minhdn1 commented on ClearKeep/App/Resources/Localize.strings
> +"General.Closse" = "Closse";
fix complete

2022-08-03 09:01 UTC, Minhdn1 commented on ClearKeep/App/Resources/Localize.strings
> +"AdvancedServer.Message.Error" = "Wrong server URL.Please try again";
fix complete

2022-08-04 02:39 UTC, vmo-klinh approved these changes

2022-08-04 02:39 UTC, merged