Feature/Group/CLK-32-906-Group-Detail
ClearKeep/ck-ios pull request #30
Opened 2022-03-28 09:49 UTC by Minhdn1

## Prerequisite
- [x] Self-review :monocle_face:
- [x] No Crashes ☠️
---

### Root cause
- UI Screen Group Detail

### Solution
- // Explain how you fix it

### Impact
- UI Screen Group Detail

### Screenshots (Optional)
- Dark
- 
<img src="https://user-images.githubusercontent.com/100137499/160372127-9ad2f22d-2409-448b-b9b4-364ea23bfb97.png)" width="200" height="430">
<img src="https://user-images.githubusercontent.com/100137499/160372195-77626127-79a6-4e5c-83fd-05f99953bda4.png)" width="200" height="430">
<img src="https://user-images.githubusercontent.com/100137499/160372212-40bba88c-889b-450a-9d0b-9621992faa33.png)" width="200" height="430">
<img src="https://user-images.githubusercontent.com/100137499/160372222-dbad6d06-72e2-4a60-b87e-9b689a50e088.png)" width="200" height="430">

- Light

<img src="https://user-images.githubusercontent.com/100137499/160372491-1d7bb7de-133f-4be8-8570-5ef1ea318517.png)" width="200" height="430">
<img src="https://user-images.githubusercontent.com/100137499/160372511-78513c9f-1d0e-48f6-852e-e75c49039d04.png)" width="200" height="430">
<img src="https://user-images.githubusercontent.com/100137499/160372524-4bd49b7a-0427-44f1-8e52-7c410a617d43.png)" width="200" height="430">
<img src="https://user-images.githubusercontent.com/100137499/160372538-4125d81c-39c6-436f-b556-331613c48366.png)" width="200" height="430">

2022-03-28 09:49 UTC, namnh92 commented
<!--
  0 Errors
  1 Warning: Big PR
  0 Messages
  19 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

- [ ] I understand that "Search.Placehodel".localized : "General.Search" is now existed in Localized service

- [ ] I understand that "General.Notification" is now existed in Localized service

- [ ] I understand that "Home.Profile" is now existed in Localized service

- [ ] I understand that "Home.Sever" is now existed in Localized service

- [ ] I understand that "GroupDetail.AddMember" is now existed in Localized service

- [ ] I understand that "GroupDetail.Search" is now existed in Localized service

- [ ] I understand that "GroupDetail.TitleCheckbox" is now existed in Localized service

- [ ] I understand that "General.Audio" is now existed in Localized service

- [ ] I understand that "General.Video" is now existed in Localized service

- [ ] I understand that "GroupDetail.RemoveMember" is now existed in Localized service

- [ ] I understand that "GroupDetail.SeeMembers" is now existed in Localized service

- [ ] I understand that "Home.Signout" is now existed in Localized service

- [ ] I understand that "General.Search" is now existed in Localized service

- [ ] I understand that "GroupDetail.UserInitTitle" is now existed in Localized service

- [ ] I understand that "Search.All" is now existed in Localized service

- [ ] I understand that "Search.GroupChat" is now existed in Localized service

- [ ] I understand that "Search.Message" is now existed in Localized service

- [ ] I understand that "Search.People" is now existed in Localized service

- [ ] I understand that "Search.Group" is now existed in Localized service

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2022-04-04 03:10 UTC, namnh92 requested changes

2022-04-04 03:10 UTC, namnh92 commented on ClearKeep/App/Theme/AppImageSet.swift
> +	var checkMask: Image { Image(systemName: "circle.fill") }
@Minhdn1 : Please get icon from figma

2022-04-04 03:10 UTC, namnh92 commented on ClearKeep/App/Theme/AppImageSet.swift
>  	var checkMaskFill: Image { Image(systemName: "checkmark.circle.fill") }
@Minhdn1 : Please get icon from figma

2022-04-04 03:24 UTC, Minhdn1 commented on ClearKeep/App/Theme/AppImageSet.swift
> +	var checkMask: Image { Image(systemName: "circle.fill") }
fix complete

2022-04-04 03:24 UTC, Minhdn1 commented on ClearKeep/App/Theme/AppImageSet.swift
>  	var checkMaskFill: Image { Image(systemName: "checkmark.circle.fill") }
fix complete

2022-04-04 04:47 UTC, namnh92 approved these changes

2022-04-04 04:47 UTC, merged